### ISSUE TITLE
helper/Nightmare.js const co = require('co') fail

### ISSUE THREAD

**Issue by politsin** [Codeception/CodeceptJS#1061]
#### What are you trying to achieve?
Init Nightmare
#### What do you get instead?
# Error: require('co') fails proccess
`const co = require('co');` - not used in
Here: https://github.com/Codeception/CodeceptJS/blob/master/lib/helper/Nightmare.js#L12

```bash
Could not load helper Nightmare from module './helper/Nightmare':
Cannot find module 'co'
Error:
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/codeceptjs/lib/helper/Nightmare.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

### Details

* CodeceptJS version: v1.1.8
* NodeJS Version: v10.1.0
* Operating System: Ubuntu 18.04
* Protractor || WebDriverIO || Nightmare version (if related): Nightmare ^3.0.1
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "url": "https://ya.ru",
      "show": false,
      "restart": false
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "myproj",
  "translation": "ru-RU"
}
```

**Comment by DavertMik** [comment]
Thanks! That should be fixed

**Comment by maciejkocol** [comment]
I'm still getting the same issue. My tests - which work perfectly fine for me with WebDriverIO - stop working as soon as I add `"Nightmare": {}` to my codecept.json. Upon trying to run my tests, the error I get is:

```
Could not load helper Nightmare from module './helper/Nightmare':
Cannot find module 'co'
```
