### ISSUE TITLE
Step-by-step Report failed to save screenshot

### ISSUE THREAD

**Issue by tsuemura** [Codeception/CodeceptJS#1413]
#### What are you trying to achieve?

I want to take step by step report. but now it fails because of the problem of resolving path.

```
    › Screenshot is saving to /home/suemura/Work/codeceptjs-sample/record_stepbystep_1546741916/0000.png
    › <Can't save step screenshot: Error: ENOENT: no such file or directory, open '/home/suemura/Work/codeceptjs-sample/record_stepbystep_1546741916/0000.png'> undefined
```

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
$ npm run test -- --grep stepbystep --verbose

> codeceptjs-sample@1.0.0 test /home/suemura/Work/codeceptjs-sample
> codeceptjs run --debug "--grep" "stepbystep" "--verbose"

creating output directory: /home/suemura/Work/codeceptjs-sample/output
CodeceptJS v2.0.2
Using test root "/home/suemura/Work/codeceptjs-sample"
Helpers: REST, Puppeteer, FetchMail, ForceClick, Ssh
Plugins: screenshotOnFail, stepByStepReport

Regression Test --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  stepbystep
    Emitted | test.before ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I am on page "https://google.com")
    Emitted | step.after (I am on page "https://google.com")
    Emitted | step.start (I am on page "https://google.com")
    I am on page "https://google.com"
    › [Url] https://www.google.com/
    › Screenshot is saving to /home/suemura/Work/codeceptjs-sample/record_stepbystep_1546741916/0000.png
    › <Can't save step screenshot: Error: ENOENT: no such file or directory, open '/home/suemura/Work/codeceptjs-sample/record_stepbystep_1546741916/0000.png'> undefined
    Emitted | step.passed (I am on page "https://google.com")
    Emitted | step.finish (I am on page "https://google.com")
    Emitted | test.passed ([object Object])
    Emitted | test.finish ([object Object])
  ✔ OK in 1371ms

    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

  OK  | 1 passed   // 2s
    Emitted | global.result ([object Object])
◉ Step-by-step preview: file:///home/suemura/Work/codeceptjs-sample/output/records.html
    Emitted | global.after ([object Object])```

> Provide test source code if related

```js
Feature('Regression Test');

Scenario('stepbystep', async (I) => {
  I.amOnPage('https://google.com')
})
```

### Details

* CodeceptJS version: 2.0.2
* NodeJS Version: v10.14.2
* Operating System: Ubuntu 18.04
* WebDriverIO version 5.2.2
* Configuration file:

I tried WebDriver and puppeteer helper but both failed

```js
require('dotenv').config()

exports.config = {
  output: './output',
  helpers: {
    REST: {
      endpoint: process.env.API_ENDPOINT,
      timeout: 30000,
    },
    WebDriver: {
      url: process.env.BASE_URL,
      browser: 'chrome',
      smartWait: 5000,
      waitForTimeout: 30000
    },
    FetchMail: {
      require: './helpers/fetchmail_helper.js'
    },
    ForceClick: {
      require: './helpers/forceClick.js'
    },
    Ssh: {
      require: './helpers/ssh.js'
    }
  },
  include: {
    I: './steps/actor.js',
    itemPage: './pages/item.js'
  },
  mocha: {},
  bootstrap: null,
  teardown: null,
  hooks: [],
  gherkin: {},
  plugins: {
    stepByStepReport: {
      enabled: true,
      deleteSuccessful: false,
    }
  },
  tests: './specs/*.js',
  name: 'codeceptjs-sample'
}
```

**Comment by kehao95** [comment]
Same issue here!

**Comment by tsuemura** [comment]
In version 2.0.3, This bug was fixed. Thank you!
However, this plugin now saves images, but it does not register images in HTML reports.

![image](https://user-images.githubusercontent.com/17092259/51025964-c8567180-15d0-11e9-9198-51d395e5c225.png)


```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Step by Steps Report</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Step by Step Report
            </a>
        </div>
    </nav>
    <div class="container">
        <h1>Recorded <small>@ Fri Jan 11 2019 18:32:21 GMT+0900 (Japan Standard Time)</small></h1>
        <ul>
            
        </ul>
    </div>

</body>
</html>
```

**Comment by tsuemura** [comment]
I'm sorry, comment https://github.com/Codeception/CodeceptJS/issues/1413#issuecomment-453454675 was caused by WebdriverIO version. I using v5.x but step-by-step report not compatible this version.
I tried with the correct WebdriverIO version and confirmed it to work fine. Thank you. I close this issue :smile:

**Comment by schmkr** [comment]
Using version 2.0.3, this still fails for me (with Puppeteer):

```
› Screenshot is saving to /Users/me/projects/a/tmp/output/record_I_can_sign_up_for_a__1547807650/0000.png
    › <Can't save step screenshot: Error: ENOENT: no such file or directory, open '/Users/me/projects/a/tmp/output/record_I_can_sign_up_for_a__1547807650/0000.png'> undefined
```

What I also notice, is that I have configured the `output` property of the stepByStepReport helper to be `./tmp/output/step-by-step/`. The HTML file is generated there, but the screenshots don't seem to be:

```
  OK  | 5 passed   // 1m
    Emitted | global.result ([object Object])
◉ Step-by-step preview: file:///Users/me/projects/a/tmp/output/step-by-step/records.html
```
