### ISSUE TITLE
click() other elements

### ISSUE THREAD

**Issue by kidandcat** [Codeception/CodeceptJS#146]
It would be great if click() method would work with other elements, for me at least it is common to have divs with click listeners.

**Comment by aldarund** [comment]
+1

**Comment by Kyderman** [comment]
+1

Especially for many calendar frameworks where the table elements are clickable etc.

**Comment by DavertMik** [comment]
Thanks, I will improve that in next release

**Comment by chozzz** [comment]
+1

**Comment by divad4686** [comment]
+1

**Comment by lovetostrike** [comment]
Is there any update or workaround for this issue?

**Comment by sivnz** [comment]
+1

**Comment by aryzle** [comment]
+1

**Comment by panique** [comment]
+1

**Comment by NikolajLeischner** [comment]
+1

It is common for any type of element to be clickable.

**Comment by yumartynova** [comment]
+1

**Comment by MarkMcCorrie** [comment]
Is there are workaround for this?

**Comment by kidandcat** [comment]
@MarkMcCorrie I think you can click any element using executed javascript inside the website, but it's a dirty workaround. It looks like this milestone will go for long.

**Comment by MarkMcCorrie** [comment]
@kidandcat I used the click method using an XPath to get it working in the end

**Comment by reubenmiller** [comment]
@DavertMik Is this resolved now in v1.1.0?

**Comment by ajusa** [comment]
Still an issue for me:  Clickable //div[@id='MainContent_FormView1_dvValidateFW']/table/tbody/tr/td[2]/div/a/span was not found by text|CSS|XPath

Even with XPath, I cannot click a span

**Comment by ChadOnlineFuels** [comment]
+1

**Comment by bmansell** [comment]
+1

**Comment by PeterNgTr** [comment]
probably we close this.
