### ISSUE TITLE
shell not working -> TypeError: recorder.finishHandler is not a function

### ISSUE THREAD

**Issue by aldarund** [Codeception/CodeceptJS#147]
$ codeceptjs shell

> Test root is assumed to be C:\Users\ShapeR\PycharmProjects\ratest
> String interactive shell for current suite...
> C:\Users\ShapeR\PycharmProjects\ratest\node_modules\codeceptjs\lib\command\interactive.js:18
>   recorder.finishHandler(() => event.dispatcher.emit(event.test.teardown));
>            ^
> 
> TypeError: recorder.finishHandler is not a function
>     at Command.module.exports (C:\Users\ShapeR\PycharmProjects\ratest\node_modules\codeceptjs\lib\command\interactive.js:18:12)
>     at Command.listener (C:\Users\ShapeR\PycharmProjects\ratest\node_modules\commander\index.js:301:8)
>     at emitTwo (events.js:100:13)
>     at Command.emit (events.js:185:7)
>     at Command.parseArgs (C:\Users\ShapeR\PycharmProjects\ratest\node_modules\commander\index.js:615:12)
>     at Command.parse (C:\Users\ShapeR\PycharmProjects\ratest\node_modules\commander\index.js:458:21)
>     at Object.<anonymous> (C:\Users\ShapeR\PycharmProjects\ratest\node_modules\codeceptjs\bin\codecept.js:84:9)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)

**Comment by DavertMik** [comment]
Fixed in 0.4.0

**Comment by lucidtech** [comment]
running 0.4.1... I'm still getting it

```
i74nr7wmt0w37hmg0d:phasma lucidtech$ codeceptjs
CodeceptJS v0.4.1

  Usage:  [options] [command]


  Commands:

    init [path]                   Creates dummy config in current dir or [path]
    shell|sh [path]               Interative shell
    list|l [path]                 List all actions for I.
    def [path]                    List all actions for I.
    generate|gt [path]            Generates an empty test
    generate|gpo [path]           Generates an empty page object
    generate|go [options] [path]  Generates an empty support object (page/step/fragment)
    generate|gh [path]            Generates a new helper
    run [options] [suite] [test]  Executes tests

  Options:

    -h, --help  output usage information

i74nr7wmt0w37hmg0d:phasma lucidtech$ codeceptjs shell
Test root is assumed to be /Users/lucidtech/ncryptify/keysecure/userportal/phasma
String interactive shell for current suite...
/usr/local/lib/node_modules/codeceptjs/lib/command/interactive.js:18
  recorder.finishHandler(() => event.emit(event.test.teardown));
           ^

TypeError: recorder.finishHandler is not a function
    at Command.module.exports (/usr/local/lib/node_modules/codeceptjs/lib/command/interactive.js:18:12)
    at Command.listener (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
    at Command.parseArgs (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/codeceptjs/bin/codecept.js:85:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by silvioluiz** [comment]
Bug still in version 0.4.3 (using Windows 7 64 bits):

![image](https://cloud.githubusercontent.com/assets/1054587/17638015/c81fe658-60bd-11e6-9f85-bb07ba48018f.png)

**Comment by silvioluiz** [comment]
@DavertMik reopen please :'(
