### ISSUE TITLE
Browser doens't close after tests finished

### ISSUE THREAD

**Issue by APshenkin** [Codeception/CodeceptJS#176]
1. Set `restart:false` option
2. Launch tests suite. at least one test should fail.
3. Note that after tests finished, the browser will be still launched

**Comment by DavertMik** [comment]
Thanks for the report. Checking it

**Comment by DavertMik** [comment]
Fixed by #196

**Comment by romal-fitbmc** [comment]
Is not fixed.
Option restart: false/true - does not matter - the last opened browser does not close (protractor).

**Comment by mycarrysun** [comment]
I can repro - it may have been broken after it was fixed in #196 

My config
```json
{
  "tests": "./test/*_test.js",
  "timeout": 10000,
  "output": "./test/output",
  "helpers": {
    "WebDriverIO" : {
      "url": "http://localhost:8080",
      "browser": "chrome",
      "restart": false,
      "windowSize": "maximize",
      "timeouts": {
        "script": 60000,
        "page load": 10000
      },
      "desiredCapabilities":{
        "chromeOptions":{
          "args": ["--aggressive-cache-discard"]
        }
      }
    }
  },
  "include": {
    "I": "./test/steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "staff"
}
```

**Comment by LukoyanovE** [comment]
@mycarrysun, this was fixed for WebDriverIO in #1113  pull request
We are waiting for release :)

See #1069 issue
