### ISSUE TITLE
Issue with running multiple test scripts w/ WebDriverIO. Unhandled promise rejection

### ISSUE THREAD

**Issue by artiomnist** [Codeception/CodeceptJS#241]
When running all of my test scripts, the first Feature will pass, but the rest will receive the following error:

```
A session id is required for this command but wasn't found in the response payload

(node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: A session id is required for this command but wasn't found in the response payload
(node:11) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

`NPM - 3.10.3`
`codeceptjs - 0.4.6`
`node - 6.7.0`
`WebDriverIO - 4.2.16`

This **was** previously working on `codeceptjs 0.4.5`, And works if I roll back to `codeceptjs 0.4.5`

Running a single test script, (e.g. `codeceptjs run . --grep "@header"` ) Works perfectly fine.

Any thoughts?

**Comment by APshenkin** [comment]
Do you use `restart:false` option?
If yes, there is an issue and PR, please check https://github.com/Codeception/CodeceptJS/pull/240

**Comment by artiomnist** [comment]
Yes, I have that option set in the codeceptjs config.
Seems to be the issue... I'll way for the request to be merged, and report any issues if they persist. 
Thanks!

**Comment by artiomnist** [comment]
Issue has been fixed in version 0.4.7 with the merging of PR #240.
Thanks a bunch guys! Keep up the awesome work!

**Comment by thesupad** [comment]
Hello,

Got here by google and it seems the problem is back as i encountered it today. :)

**Comment by joelgrimberg** [comment]
same here. I do not use the restart option (neither restart: false nor restart:true)

**Comment by waryhermit** [comment]
I am also getting
` [6] Error | Error: A session id is required for this command but wasn't found in the response payload`
on tests after the first test.

**Comment by APshenkin** [comment]
Please, provide your test to reproduce the issue

**Comment by waryhermit** [comment]
@APshenkin I'll link you to our tests. If I get some free time I might try to make a trimmed down reproducible case.

[codecept.conf.js](https://github.com/ole-vi/BeLL-Apps/blob/dev/tests/codecept.conf.js)
[saucelabs_helper.js](https://github.com/ole-vi/BeLL-Apps/blob/dev/tests/saucelabs_helper.js)
[steps_file.js](https://github.com/ole-vi/BeLL-Apps/blob/dev/tests/steps_file.js)
[codeceptjs-init.js](https://github.com/ole-vi/BeLL-Apps/blob/dev/tests/codeceptjs-init.js)
[login_test.js](https://github.com/ole-vi/BeLL-Apps/blob/dev/tests/login_test.js)
[resource_test.js](https://github.com/mappuji/BeLL-Apps/blob/400d0e4b024cfe01dd5c565a7783992b9c318cc0/tests/resource_test.js)

Travis CI log with error and codeceptjs verbose:
https://travis-ci.org/ole-vi/BeLL-Apps/builds/210193040#L1159

**Comment by waryhermit** [comment]
I only have this issue when the tests are running on Travis, not when running them locally.

@thesupad @joelgrimberg Did either you figure out what the problem was? Do you run into this error when running the tests locally or only on a CI build system?

**Comment by tfiwm** [comment]
I have the same issue with when i am using it  with Browserstack:

NPM - 3.10.10
codeceptjs - 0.6.2
node - 6.10.0
WebDriverIO - 4.8.0

**Comment by mikhailpractice** [comment]
Just reproduced it again

**Comment by shamili12** [comment]
Still face the same err "Error: A session id is required for this command but wasn't found in the response payload". Can someone guide me what the err actually means?
Thanks!
